ong-bitcoin-argentina/DIDI-SSI-Docs

- docs/contributing.md
- Nueva sección sobre pull request en las contribuciónes
- Ignorar problemas de deploy con Vercel
> docs(contributing): add pull request section

- docs/aidi-definiciones.md
- docs/arquitectura.md
- docs/emisor-credenciales.md
- sidebars.js
La documentación de producto quedó separada en tres secciones:
* aidi-definiciones
* producto-emisores
* arquitectura [a actualizar y completar]
> abrir en secciones la documentacion de producto

- docs/conceptos.md
- Corrección de algunos errores de tipeo y ortografía.
- Traducción de "Conceptos Importantes"
> Actualización de la pagina conceptos importantes

- docs/arquitectura-server.md
Verificar el código y actualizar la información acerca de la verificación de identidad, en la sección de Developers / Descripción tecnica / Server.
> Actualizar informacion de verificacion de identidad MM-42 

- docs/arquitectura-server.md
- docs/contributing.md
Indicaciones para instalar global commitizen en caso de problemas
> Actualizar guía de contribución

- docs/arquitectura-issuer.md
Describir con mas detalle las rutas /register
> Actualizar descripción del Issuer-back

- docs/arquitectura-issuer.md
- docs/arquitectura-server.md
Especificar información de cada endpoint de didi-server
> Documentar Endpoints

- docs/ssi/ssi-concepts.md
correcciones texto ssi (según branch preview)
> correcciones texto ssi

- docs/aidi/aidi-beneficios.md
- docs/developers/solucion/descripcion-tecnica/delegation.md
correccion textos aidi-beneficios y delegation (revisión vercel)
> correccion textos aidi-beneficios y delegation

- docs/emisores/emisores-plataforma.md
correcciones texto emisores-plataforma (verificacion vercel)
> correcciones texto emisores-plataforma

- docs/developers/deployment/post-deployment.md
- sidebars.js
- yarn.lock
Agregado de todo el procedimiento de config post-deployment
> Agregado de Proc. Post-Deployment

- docs/changelog.md
- sidebars.js
* Se agrega nueva sección changelog
> Add changelog section

- docs/v0.5.x.md
> changelog v0.5.7

- docs/v0.5.x.md
Se agregaron cambios de la versión 0.5.11.
Se actualizo la fecha de la versión 0.5.10.
> Se agregaron cambios de la versión 0.5.11

- docs/v0.5.x.md
Se agregan cambios de la versión 0.5.12
> Cambios en la versión 0.5.12

- docs/developers/solucion/arquitectura-overview.md
Actualización overview arquitectura
> Update architecture overview

- docs/developers/deployment/post-deployment.md
- docs/developers/solucion/descripcion-tecnica/arquitectura-server.md
- Se actualiza el post a realizar al delegar un issuer
- Se actualizan las rutas de /issuer a su estado actual en la ultima versión
> Mm 458/ Actualizar info sobre delegaciones

- docs/developers/deployment/post-deployment.md
- Se actualizan las url para los llamados de issuer backend y didi server
> Actualizar url base

- docs/changelog/v0.6.x.md
> Actualizar changelog

- docs/contribuciones/contribuciones.md
Se agregan las versiones de aidi y se taguea el repo.
> versionado aidi

- docs/contribuciones/contribuciones.md
Se agregan las versiones de ronda y se taguea el repo.
> versionado apps ronda

- docs/changelog-aidi/v1.5.x.md
se agrego las siguientes cambios:
[ai·di] se implementó la captura del frente del documento por vuSecurity
[ai·di] se implementó la cancelación de la validación de identidad por vuSecurity
[ai·di] se implementó el inicio de la validación de identidad por vuSecurity
[ai·di] se eliminó antiguo cartel rojo de validación 
[ai·di] se agregó navegación del botón de validar con renaper 
[ai·di] se agregó navegación del botón de validar con semillas 
[ai·di] se corrigió pantalla de inicio 
[ai·di] se agregó nueva pantalla con todas las validaciones de identidad
> add_changes_first

- docs/ssi/ssi-concepts.md
Cambio en la redacción de de los principios de SSI
> Fix ssi concepts

- docs/changelog-system/v0.8.x.md
- Se agregan los cambios de la v0.8.1
> Changelog - v0.8.1

- docs/changelog-aidi/v1.5.x.md
- docs/changelog-aidi/v1.6.x.md
- sidebars.js
DIDI-SSI-Docs:
- documentation correction
- new version added
> Vus 154 aidi 1.6.0 add changes to the documentation

- docs/aidi/aidi-validacionIdentidad.md
- docs/changelog-aidi/v1.6.x.md
- docs/developers/solucion/descripcion-tecnica/arquitectura-aidi.md
- sidebars.js
DIDI-SSI-Docs:
- complete and updated documentation
> complete and updated documentation

- docs/developers/solucion/descripcion-tecnica/arquitectura-mouro.md
Actualización funcionamiento Mouro
[VUS-236](https://proyecto-didi.atlassian.net/browse/VUS-236), [VUS-237](https://proyecto-didi.atlassian.net/browse/VUS-237)
> Update Mouro backup file description

- docs/developers/solucion/descripcion-tecnica/arquitectura-issuer.md
Se eliminan las rutas para evitar mantenimiento duplicado
> Issuer: Cambios menores en la descripción

- docs/changelog-aidi/v1.6.x.md
- yarn.lock
DIDI-SSI-Docs: 
* Se a registrado los cambio efectuado en las versión v1.6.3  y  v1.6.4
* v1.6.3 : corresponde a mantenimiento y mejoras más el servicio de Coopsol.
* v1.6.4: corresponde a multi-emisores.
> fix: changelog has been updated
